<?xml version="1.0"?>
<robot name="wheelchair" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- useful definition -->
    <xacro:property name="halfpi" value="1.57079633" />
    <xacro:property name="sixthpi" value="0.523598776" />

    <!-- wheelchair properties -->
    <xacro:property name="wheel_diameter" value="0.34" />
    <xacro:property name="wheel_thickness" value="0.06" />

    <!-- Robot movement base representation -->
    <xacro:property name="robot_base_height" value="0.45" />
    <xacro:property name="robot_base_length" value="0.6" />
    <xacro:property name="robot_base_width" value="0.4" />

    <xacro:property name="robot_base_offset_height" value="0.05" />
    <xacro:property name="robot_wheelbase_offset" value="0.15" />

    <!-- footrest -->
    <xacro:property name="footrest_length" value="0.2" />
    <xacro:property name="footrest_width" value="0.31" />
    <xacro:property name="footrest_height" value="0.01" />
    <xacro:property name="footrest_offset" value="0.02" />

    <!-- sonar -->
    <xacro:property name="sonar_length" value="0.015" />
    <xacro:property name="sonar_width" value="0.045" />
    <xacro:property name="sonar_height" value="0.02" />
    <xacro:property name="sonar_fwd_offset" value="0.0325" />
    <xacro:property name="sonar_side_fwd_offset" value="0.04" />
    <xacro:property name="sonar_side_offset" value="0.055" />
    <xacro:property name="sonar_angle" value="0.7" />

    <!-- kinect -->
    <xacro:property name="kinect_stand_height" value="1.18" />
    <xacro:property name="kinect_stand_diameter" value="0.039" />

    <!-- chair -->
    <xacro:property name="backrest_height" value="0.65" />
    <xacro:property name="backrest_thickness" value="0.15" />
    <xacro:property name="backrest_width" value="0.45" />

    <!-- arms -->
    <xacro:property name="arm_height" value="0.06" />
    <xacro:property name="arm_width" value="0.07" />
    <xacro:property name="left_arm_length" value="0.38" />
    <xacro:property name="right_arm_length" value="0.6" />
    <xacro:property name="arm_offset_vertical" value="0.15" />

    <!-- end wheelchair properties -->

    <!-- Colors -->
    <xacro:macro name="color_blue">
        <material name="blue">
            <color rgba="0 0 0.75 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_yellow">
        <material name="yellow">
            <color rgba="0.75 0.75 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_red_green">
        <material name="red_green">
            <color rgba="1.0 1.0 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_black">
        <material name="black">
            <color rgba="0.1 0.1 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_gray">
        <material name="dark_gray">
            <color rgba="0.3 0.3 0.3 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_gray">
        <material name="gray">
            <color rgba="0.5 0.5 0.5 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_silver">
        <material name="silver">
            <color rgba="0.9 0.9 0.9 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_green">
        <material name="green">
            <color rgba="0 0.75 0.1 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_olive">
        <material name="olive">
            <color rgba="0.5 0.5 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_orange">
        <material name="orange">
            <color rgba="1.0 0.65 0 1.0" />
        </material>
    </xacro:macro>
    
    <xacro:macro name="color_aqua">
        <material name="aqua">
            <color rgba="0.25 0.3 0 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_dark_purple">
        <material name="dark_purple">
            <color rgba="0.3 0 0.3 1.0" />
        </material>
    </xacro:macro>

    <xacro:macro name="color_magenta">
        <material name="magenta">
            <color rgba="1.0 0 1.0 0.5" />
        </material>
    </xacro:macro>
    <!-- end colors -->

    <!-- useful macros -->
    <xacro:macro name="prism" params="name x y z *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
                <xacro:insert_block name="color" />
            </visual>
            <collision>
                <geometry>
                    <box size="${x} ${y} ${z}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="cyl" params="name radius length *color">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <xacro:insert_block name="color" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>
    <!-- end useful macros -->

    <!-- links -->
    <!-- link that gets connected to the map, exists at ground level -->
    <link name="base_link" />

    <joint name="base_link_to_wheelchair_base" type="fixed">
        <parent link="base_link" />
        <child link="wheelchair_base" />
        <origin
            xyz="${-robot_wheelbase_offset} 0 ${robot_base_offset_height + (robot_base_height / 2)}"
            rpy="0 0 0" />
    </joint>

    <!-- Mobile base of the wheelchair, including the chair part -->
    <xacro:prism
        name="wheelchair_base"
        x="${robot_base_length}"
        y="${robot_base_width}"
        z="${robot_base_height}">
        <xacro:color_dark_gray />
    </xacro:prism>

    <!-- footrest and sonar -->
    <xacro:prism
        name="wheelchair_footrest"
        x="${footrest_length}"
        y="${footrest_width}"
        z="${footrest_height}">
        <xacro:color_black />
    </xacro:prism>

    <joint name="footrest_joint" type="fixed">
        <parent link="wheelchair_base" />
        <child link="wheelchair_footrest" />
        <origin
            xyz="${(footrest_length + robot_base_length)/2} 0 ${-robot_base_height/2 + footrest_height/2 + footrest_offset}"
            rpy="0 0 0" />
    </joint>

    <xacro:prism
        name="sonar_center"
        x="${sonar_length}"
        y="${sonar_width}"
        z="${sonar_height}">
        <xacro:color_blue />
    </xacro:prism>

    <joint name="center_sonar_joint" type="fixed">
        <parent link="wheelchair_footrest" />
        <child link="sonar_center" />
        <origin
            xyz="${sonar_fwd_offset + sonar_length/2} 0 ${-(footrest_height + sonar_height)/2}"
            rpy="0 0 0" />
    </joint>

    <xacro:prism
        name="sonar_left"
        x="${sonar_length}"
        y="${sonar_width}"
        z="${sonar_height}">
        <xacro:color_blue />
    </xacro:prism>

    <joint name="left_sonar_joint" type="fixed">
        <parent link="wheelchair_footrest" />
        <child link="sonar_left" />
        <origin
            xyz="${sonar_side_fwd_offset + sonar_length/2} ${(sonar_side_offset - sonar_width / 2)} ${-(footrest_height + sonar_height)/2}"
            rpy="0 0 ${sonar_angle}" />
    </joint>

    <xacro:prism
        name="sonar_right"
        x="${sonar_length}"
        y="${sonar_width}"
        z="${sonar_height}">
        <xacro:color_blue />
    </xacro:prism>

    <joint name="right_sonar_joint" type="fixed">
        <parent link="wheelchair_footrest" />
        <child link="sonar_right" />
        <origin
            xyz="${sonar_side_fwd_offset + sonar_length/2} ${-(sonar_side_offset - sonar_width / 2)} ${-(footrest_height + sonar_height)/2}"
            rpy="0 0 ${-sonar_angle}" />
    </joint>

    <!-- Left wheel of the wheelchair -->
    <xacro:cyl
        name="wheelchair_left_wheel"
        radius="${wheel_diameter / 2}"
        length="${wheel_thickness}">
        <xacro:color_gray />
    </xacro:cyl>

    <joint name="wheelchair_base_to_left_wheel" type="fixed">
        <parent link="wheelchair_base" />
        <child link="wheelchair_left_wheel" />
        <origin
            xyz="${robot_wheelbase_offset} ${((robot_base_width + wheel_thickness) / 2)} ${-(robot_base_offset_height + (robot_base_height / 2)) + (wheel_diameter / 2)}"
            rpy="${-halfpi} 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <!-- Right wheel of the wheelchair -->
    <xacro:cyl
        name="wheelchair_right_wheel"
        radius="${wheel_diameter / 2}"
        length="${wheel_thickness}">
        <xacro:color_gray />
    </xacro:cyl>

    <joint name="wheelchair_base_to_right_wheel" type="fixed">
        <parent link="wheelchair_base" />
        <child link="wheelchair_right_wheel" />
        <origin
            xyz="${robot_wheelbase_offset} ${-((robot_base_width + wheel_thickness) / 2)} ${-(robot_base_offset_height + (robot_base_height / 2)) + (wheel_diameter / 2)}"
            rpy="${halfpi} 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <!-- Upright part of the wheelchair's chair -->
    <xacro:prism
        name="wheelchair_upright"
        x="${backrest_thickness}"
        y="${backrest_width}"
        z="${backrest_height}">
        <xacro:color_black />
    </xacro:prism>

    <joint name="upright_joint" type="fixed">
        <parent link="wheelchair_base" />
        <child link="wheelchair_upright" />

        <origin
            xyz="${-(robot_base_length / 2) + backrest_thickness / 2 + kinect_stand_diameter} 0 ${(robot_base_height / 2) + (backrest_height / 2)}"
            rpy="0 0 0" />
    </joint>

    <!-- Left arm of the wheelchair, does not have the joystick -->
    <xacro:prism
        name="wheelchair_left_arm"
        x="${left_arm_length}"
        y="${arm_width}"
        z="${arm_height}">
        <xacro:color_black />
    </xacro:prism>

    <joint name="left_arm_joint" type="fixed">
        <parent link="wheelchair_upright" />
        <child link="wheelchair_left_arm" />
        <origin
            xyz="${(left_arm_length - backrest_thickness) / 2} ${(arm_width + backrest_width) / 2} ${-(backrest_height) / 2 + arm_offset_vertical}"
            rpy="0 0 0" />
    </joint>

    <!-- Right arm of the wheelchair, includes a joystick -->
    <xacro:prism
        name="wheelchair_right_arm"
        x="${right_arm_length}"
        y="${arm_width}"
        z="${arm_height}">
        <xacro:color_black />
    </xacro:prism>

    <joint name="right_arm_joint" type="fixed">
        <parent link="wheelchair_upright" />
        <child link="wheelchair_right_arm" />
        <origin
            xyz="${(right_arm_length - backrest_thickness) / 2} ${-(arm_width + backrest_width) / 2} ${-(backrest_height) / 2 + arm_offset_vertical}"
            rpy="0 0 0" />
    </joint>

    <!-- Carbon-fiber pole that extends upwards from the chair -->
    <xacro:cyl
        name="kinect_stand"
        radius="${kinect_stand_diameter / 2}"
        length="${kinect_stand_height}">
        <xacro:color_black />
    </xacro:cyl>

    <joint name="kinect_stand_joint" type="fixed">
        <parent link="wheelchair_base" />
        <child link="kinect_stand" />
        <origin
            xyz="${-(robot_base_length - kinect_stand_diameter) / 2} ${(robot_base_width - kinect_stand_diameter) / 2} ${(robot_base_height + kinect_stand_height) / 2}"
            rpy="0 0 0" />
    </joint>

    <!-- kinect representation -->
    <xacro:prism name="camera_link" x="0.06" y="0.285" z="0.035">
        <xacro:color_black />
    </xacro:prism>

    <joint name="kinect_joint" type="revolute">
        <parent link="kinect_stand" />
        <child link="camera_link" />
        <origin
            xyz="0 0 ${kinect_stand_height / 2}"
            rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="${-sixthpi}" upper="${sixthpi}" effort="1" velocity="1" />
    </joint>
</robot>
