set(_CATKIN_CURRENT_PACKAGE "go_to_goal_turtlesim")
set(go_to_goal_turtlesim_VERSION "0.0.0")
set(go_to_goal_turtlesim_MAINTAINER "wcm-mob <wcm-mob@todo.todo>")
set(go_to_goal_turtlesim_PACKAGE_FORMAT "2")
set(go_to_goal_turtlesim_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(go_to_goal_turtlesim_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(go_to_goal_turtlesim_BUILDTOOL_DEPENDS "catkin")
set(go_to_goal_turtlesim_BUILDTOOL_EXPORT_DEPENDS )
set(go_to_goal_turtlesim_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(go_to_goal_turtlesim_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(go_to_goal_turtlesim_TEST_DEPENDS )
set(go_to_goal_turtlesim_DOC_DEPENDS )
set(go_to_goal_turtlesim_URL_WEBSITE "")
set(go_to_goal_turtlesim_URL_BUGTRACKER "")
set(go_to_goal_turtlesim_URL_REPOSITORY "")
set(go_to_goal_turtlesim_DEPRECATED "")